### ISSUE TITLE
Failing to push to Power Apps environment

### ISSUE THREAD

**Issue by Ello-Avery** [afrose-97/ExportToExcel#1]
I attempted to push the component to my environment as per the md file. I used the following command after I successfully authenticated: 

pac pcf push --publisher-prefix eavery

It came with the following error

Connected as <My Email>
Connected to... <My Org>
Using publisher prefix 'eavery'.
Checking if the control 'eavery_exportToExcelNS.exportToExcel' already exists in the current org.
Using full update.
Creating a temporary solution wrapper to push the component.
Sorry, the app encountered a non recoverable error and will need to terminate. The exception details have been captured and will be forwarded to the development team, if telemetry has been enabled. Exception Id: 5d9ace38-99c6-439c-959c-c2baa18e8287, Exception Type: System.ArgumentException
The diagnostic logs can be found at: 

Any thoughts on what could be causing this?

**Comment by afrose-97** [comment]
Hi, would recommend you to go through the [link](https://carldesouza.com/pcf-create-build-deploy-cheat-sheet/). Please reach out to posttoafrose@gmail.com if the issue persists.
